'use client';

import { useCallback, useEffect, useRef, useState, type CSSProperties } from 'react';
import { ArrowUpRight, ArrowDown, Plus, MoveUpRight, Pause, Play, Check, FileText, Layers, Sparkles, Sun, Coffee, BookOpen, Heart, CalendarDays, Users, ArrowRight } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import Scene from './scene';

const Arrow = () => <ArrowUpRight size={19} strokeWidth={1.5}/>;
const phrase = 'The world is complex. Work doesn’t have to be.';

export default function Home() {
  const root = useRef<HTMLElement>(null);
  const [loaded,setLoaded] = useState(false);
  const [progress,setProgress] = useState(0);
  const [paused,setPaused] = useState(false);
  const readyRef = useRef(false);
  const onReady = useCallback(()=>{readyRef.current=true;},[]);
  useEffect(()=> { const media=window.matchMedia('(prefers-reduced-motion: reduce)'); setPaused(media.matches);const change=()=>setPaused(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
  useEffect(()=> {
    const start=performance.now();
    const interval=window.setInterval(()=>{
      const elapsed=performance.now()-start;
      setProgress(Math.min(readyRef.current ? 100 : 94,Math.round(elapsed/28)));
      if ((elapsed>2850 && readyRef.current) || elapsed>4800 || paused) {setProgress(100);setLoaded(true);window.clearInterval(interval);}
    },45);
    return()=>window.clearInterval(interval);
  },[paused]);
  useEffect(()=> {
    if(!loaded) return;
    let stop=()=>{},disposed=false;
    Promise.all([import('gsap'),import('gsap/ScrollTrigger'),import('lenis')]).then(([{gsap},{ScrollTrigger},{default:Lenis}])=>{
      if(disposed)return;
      gsap.registerPlugin(ScrollTrigger);
      const lenis = paused ? null : new Lenis({duration:1.15,smoothWheel:true,anchors:true});
      const tick=(time:number)=>lenis?.raf(time*1000);
      if(lenis){lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(tick);}
      const ctx=gsap.context(()=>{
        if(paused)return;
        gsap.fromTo('.hero-line > span',{yPercent:115,rotateX:-45},{yPercent:0,rotateX:0,duration:1.35,stagger:.13,ease:'power4.out',delay:.2});
        gsap.fromTo('.hero-art',{scale:.62,rotation:-24,opacity:0},{scale:1,rotation:0,opacity:1,duration:1.8,ease:'power3.out',delay:.05});
        gsap.fromTo('.site-header,.hero-top,.hero-bottom,.hero-caption',{y:20,opacity:0},{y:0,opacity:1,duration:1,stagger:.1,delay:.45});
        gsap.to('.hero h1',{y:-100,rotateX:12,scale:.96,transformOrigin:'left center',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});
        gsap.fromTo('.manifesto-word',{color:'#434954'},{color:'#f0f2f6',stagger:.12,ease:'none',scrollTrigger:{trigger:'.manifesto-copy',start:'top 78%',end:'bottom 40%',scrub:.6}});
        gsap.fromTo('.intro-bottom',{y:65},{y:0,scrollTrigger:{trigger:'.intro-bottom',start:'top bottom',end:'top 65%',scrub:1}});
        gsap.to('.system-copy-first',{y:-55,opacity:0,scrollTrigger:{trigger:'.transformation',start:'top -20%',end:'top -65%',scrub:.7}});
        gsap.fromTo('.system-copy-last',{y:55,opacity:0},{y:0,opacity:1,scrollTrigger:{trigger:'.transformation',start:'top -55%',end:'top -95%',scrub:.7}});
        gsap.to('.system-progress-fill',{scaleY:1,ease:'none',scrollTrigger:{trigger:'.transformation',start:'top top',end:'bottom bottom',scrub:.3}});
        gsap.to('.system-label-before',{opacity:.2,scrollTrigger:{trigger:'.transformation',start:'top -35%',end:'top -80%',scrub:.5}});
        gsap.fromTo('.system-label-after',{opacity:.2},{opacity:1,scrollTrigger:{trigger:'.transformation',start:'top -35%',end:'top -80%',scrub:.5}});
        gsap.fromTo('.work-visual',{rotateX:14,rotateY:-5,scale:.84},{rotateX:0,rotateY:0,scale:1,scrollTrigger:{trigger:'.work-visual-wrap',start:'top 92%',end:'top 14%',scrub:1}});
        gsap.fromTo('.architecture-image',{scale:1.2,yPercent:-8},{scale:1,yPercent:5,scrollTrigger:{trigger:'.work-visual',start:'top bottom',end:'bottom top',scrub:1}});
        gsap.fromTo('.structo-interface',{y:100,rotateY:-12,rotateX:10},{y:-35,rotateY:0,rotateX:0,scrollTrigger:{trigger:'.work-visual',start:'top 75%',end:'bottom 25%',scrub:1}});
        gsap.utils.toArray<HTMLElement>('.project-card').forEach((card,index)=>{
          gsap.fromTo(card,{rotateX:14,rotateY:index%2 ? 5 : -5,scale:.91,y:90},{rotateX:0,rotateY:0,scale:1,y:0,ease:'none',scrollTrigger:{trigger:card,start:'top 95%',end:'top 18%',scrub:1}});
          gsap.fromTo(card.querySelector('.project-artifact'),{rotateY:-18,rotateX:12,y:65,z:0},{rotateY:8,rotateX:-5,y:-35,z:100,ease:'none',scrollTrigger:{trigger:card,start:'top bottom',end:'bottom top',scrub:1.1}});
          gsap.fromTo(card.querySelector('.project-watermark'),{xPercent:12},{xPercent:-12,scrollTrigger:{trigger:card,start:'top bottom',end:'bottom top',scrub:1}});
        });
        gsap.fromTo('.other-heading h2',{x:-65},{x:0,scrollTrigger:{trigger:'.other-heading',start:'top 90%',end:'top 45%',scrub:.8}});
        gsap.utils.toArray<HTMLElement>('.approach-row').forEach(el=>gsap.fromTo(el,{rotateX:18,y:65},{rotateX:0,y:0,scrollTrigger:{trigger:el,start:'top 95%',end:'top 60%',scrub:.8}}));
        gsap.fromTo('.possibility-line.one',{xPercent:12},{xPercent:-12,scrollTrigger:{trigger:'.possibility',start:'top bottom',end:'bottom top',scrub:1}});
        gsap.fromTo('.possibility-line.two',{xPercent:-14},{xPercent:8,scrollTrigger:{trigger:'.possibility',start:'top bottom',end:'bottom top',scrub:1}});
        gsap.fromTo('.footer-wordmark',{yPercent:40,rotateX:45},{yPercent:0,rotateX:0,scrollTrigger:{trigger:'.site-footer',start:'top 70%',end:'bottom bottom',scrub:1}});
        gsap.to('.footer-asterisk',{rotation:150,scrollTrigger:{trigger:'.site-footer',start:'top bottom',end:'bottom bottom',scrub:1}});
      },root);
      const refresh=()=>ScrollTrigger.refresh();document.fonts.ready.then(refresh);window.addEventListener('load',refresh);ScrollTrigger.refresh();
      stop=()=>{ctx.revert();gsap.ticker.remove(tick);lenis?.destroy();window.removeEventListener('load',refresh);};
    });
    return()=>{disposed=true;stop();};
  },[loaded,paused]);

  return <main ref={root} className={`${loaded?'is-ready':''} ${paused?'motion-paused':''}`}>
    <a className="skip-link" href="#approach">Skip to content</a>
    <div className={`loader ${loaded?'loader-finished':''}`} aria-hidden={loaded} role="status" aria-label="Preparing the experience">
      <div className="loader-grid" aria-hidden="true"/><div className="loader-top"><span>INDEPENDENT MINDS.</span><span>INTELLIGENT SOFTWARE.</span></div>
      <div className="loader-center"><div className="loader-orbit" aria-hidden="true"><i/><i/><i/></div><div className="loader-brand" aria-label="Egekvist & Skovsted">{['Egekvist','& Skovsted'].map((line,row)=><div className="loader-brand-line" aria-hidden="true" key={line}>{Array.from(line).map((letter,index)=><span key={index} className={letter==='&'?'loader-amp':''} style={{'--letter-delay':`${(index+row*5)*45+180}ms`} as CSSProperties}>{letter===' '? '\u00a0':letter}</span>)}</div>)}</div><p>Making complex work feel simple.</p></div>
      <div className="loader-bottom"><span>MAKING ROOM FOR SIMPLE</span><span>{String(progress).padStart(3,'0')}%</span><Progress className="loader-progress" value={progress} aria-label="Loading experience"/></div>
    </div>
    <header className="site-header"><a className="wordmark" href="#top" aria-label="Egekvist & Skovsted home">Egekvist <span>& Skovsted</span><i>®</i></a><nav aria-label="Main navigation"><a href="#approach">Our approach</a><a href="#work">Selected work <sup>03</sup></a><a href="#other-work">Other work</a></nav><a className="contact-nav" href="mailto:mail@structo.dk">Let’s talk <span><Arrow/></span></a></header>
    <section className="hero" id="top"><div className="hero-top"><span className="eyebrow"><i className="status-dot"/> INDEPENDENT MINDS. INTELLIGENT SOFTWARE.</span><span className="edition">BUILT IN DENMARK. THINKING BEYOND.</span></div><div className="hero-art"><Scene kind="hero" paused={paused} onReady={onReady}/></div><h1 aria-label="Making complex work feel simple"><span className="hero-line"><span>Making complex</span></span><span className="hero-line"><span>work feel <em>simple.</em></span></span></h1><div className="hero-bottom"><p>We turn the work that slows the world down<br className="desktop-break"/> into software that moves it forward.</p><a className="circle-link" href="#approach"><span>SCROLL TO SIMPLIFY</span><i><ArrowDown size={20}/></i></a></div><div className="hero-caption"><span>HUMAN AMBITION × ARTIFICIAL INTELLIGENCE</span><span>01 — ∞</span></div></section>

    <section className="intro section-pad" id="approach"><div className="section-marker"><span className="eyebrow">01 / THE WAY WE SEE IT</span><Plus size={18}/></div><h2 className="manifesto-copy">{phrase.split(' ').map((word,i)=><span className="manifesto-word" key={i}>{word} </span>)}</h2><div className="intro-bottom"><span className="mini-asterisk" aria-hidden="true">✳</span><div><p>Too many brilliant minds are busy doing work that shouldn’t be hard.</p><p>We find the manual, the repetitive, the unnecessarily complex. Then we use AI to turn it into something remarkably simple. So people can get back to moving the world forward.</p></div></div></section>

    <section className="transformation" id="transformation"><div className="system-sticky"><div className="system-top"><span className="eyebrow">COMPLEXITY, RECONSIDERED.</span><span className="eyebrow">SCROLL TO TRANSFORM ↓</span></div><div className="system-copy"><div className="system-copy-first"><span className="small-index">[ BEFORE ]</span><h2>So much work.<br/>So little flow.</h2><p>Scattered information. Repeated tasks.<br/>Potential, waiting to be unlocked.</p></div><div className="system-copy-last"><span className="small-index">[ AFTER ]</span><h2>Everything<br/><em>falls into place.</em></h2><p>One intelligent system.<br/>A simpler way to move forward.</p></div></div><div className="system-art"><Scene kind="system" paused={paused}/></div><div className="system-progress"><span>01</span><div><i className="system-progress-fill"/></div><span>02</span></div><div className="system-bottom"><span className="system-label-before">FROM FRICTION</span><span className="system-bottom-line"/><span className="system-label-after">TO FLOW</span></div></div></section>

    <section className="work-section section-pad" id="work" lang="da"><div className="section-marker"><span className="eyebrow">02 / IDÉER, DER GØR EN FORSKEL</span><span className="eyebrow">UDVALGT PROJEKT — 01</span></div><div className="work-heading"><h2>Mindre rutinearbejde.<br/><span>Flere muligheder.</span></h2><p>En bedre arbejdsdag er ikke en fjern idé.<br/>Det er noget, vi bygger. Lige nu.</p></div><div className="work-visual-wrap"><div className="work-visual"><img className="architecture-image" src="/architecture.jpg" alt="Skulpturel betonarkitektur i sollys mod en blå himmel" width="1536" height="1024" loading="lazy"/><div className="visual-brand"><span className="structo-icon">▥</span> structo<span className="visual-tag">INTELLIGENS TIL BYGGEBRANCHEN</span></div><div className="structo-interface" aria-label="Illustrativt projektoverblik i Structo"><div className="interface-top"><span><span className="structo-icon">▥</span> structo</span><span className="concept-label">PLATFORMKONCEPT</span></div><div className="interface-content"><span className="interface-kicker">DIT PROJEKT. SAMLET.</span><h3>Fra krav til klarhed.</h3><div className="interface-project"><Layers size={17}/><span>Projektoversigt</span><span className="project-status"><i/> Klar til overblik</span></div>{[['Lokalplaner','Find det relevante'],['Bygningsreglementet','Forstå kravene'],['Myndighedskrav','Arbejd videre']].map(([title,text])=><div className="interface-row" key={title}><FileText size={16}/><div><strong>{title}</strong><span>{text}</span></div><Check size={15}/></div>)}<div className="interface-ai"><Sparkles size={15}/><span>Mindre søgning. Mere sammenhæng.</span></div></div></div><span className="work-visual-bottom">ET NYT PERSPEKTIV PÅ ARKITEKTUR.</span></div></div>
      <div className="work-details" lang="da"><div className="work-title"><span className="eyebrow">STRUCTO / AI TIL BYGGEBRANCHEN</span><h3>Brug mindre tid på regler.<br/><span>Mere tid på arkitektur.</span></h3><a href="https://structo.dk" target="_blank" rel="noreferrer" className="text-link">Oplev Structo <Arrow/></a></div><div className="work-description"><p>Structo hjælper arkitekter, bygningskonstruktører og andre rådgivere i byggebranchen med at bruge mindre tid på at finde og gennemgå regler og krav.</p><p>Platformen samler relevant information om et byggeprojekt og gør det lettere at finde, forstå og arbejde med blandt andet lokalplaner, bygningsreglementet og andre myndighedskrav.</p><p>Målet er enkelt: mindre tid på manuelt regelarbejde og mere tid på projektering, rådgivning og arkitektur.</p></div></div>
    </section>

    <section className="other-work" id="other-work" aria-labelledby="other-work-title">
      <div className="other-heading"><div className="section-marker"><span className="eyebrow">03 / SOFTWARE, WITH A PURPOSE</span><span className="eyebrow">THREE PROJECTS. ONE MINDSET.</span></div><h2 id="other-work-title">Other work<span>®</span></h2><div className="other-intro"><p>Different worlds.<br/>The same belief in simple.</p><span className="eyebrow">EXPLORE THE PROJECTS <ArrowDown size={16}/></span></div></div>
      <div className="projects-stage"><div className="portfolio-orbit"><Scene kind="portfolio" paused={paused}/></div>
        <article className="project-card project-picto" lang="da"><div className="project-top"><span>01 / VISUEL KOMMUNIKATION</span><span>SOFTWAREUDVIKLING</span></div><div className="project-body"><div className="project-copy"><span className="project-client">PictoPartner</span><h3>Mere struktur.<br/>Mere nærvær.</h3><p>Vi har udviklet softwaren bag PictoPartner: en platform, der samler piktogrammer, arbejdsopgaver og visuelle hjælpemidler til institutioner, specialtilbud og familier.</p><p>Fra bibliotek og egne piktogrammer til printklare materialer. Mindre manuel fremstilling giver mere plads til faglighed, omsorg og samvær.</p><a className="text-link" href="https://pictopartner.dk" target="_blank" rel="noreferrer">Oplev PictoPartner <Arrow/></a></div><div className="project-art"><div className="project-artifact picto-board"><div className="artifact-bar"><span>PictoPartner</span><span>VISUELT KONCEPT</span></div><div className="picto-board-content"><span className="artifact-eyebrow">SMÅ TRIN. EN TRYGGERE DAG.</span><h4>Min dag</h4><div className="picto-grid">{[{Icon:Sun,title:'Godmorgen'},{Icon:Coffee,title:'Morgenmad'},{Icon:BookOpen,title:'Læsetid'},{Icon:Heart,title:'Fællesskab'}].map(({Icon,title})=><div className="picto-tile" key={title}><Icon strokeWidth={1.2}/><span>{title}</span></div>)}</div><div className="artifact-note"><Check size={15}/><span>Overblik, der er til at forstå.</span></div></div></div></div></div><div className="project-bottom"><span>FRA MANUEL FREMSTILLING TIL VISUEL KLARHED</span><span>PICTOPARTNER.DK <Arrow/></span></div><span className="project-watermark" aria-hidden="true">Clarity.</span></article>
        <article className="project-card project-parish" lang="da"><div className="project-top"><span>02 / DIGITALE FÆLLESSKABER</span><span>SOFTWAREUDVIKLING</span></div><div className="project-body"><div className="project-copy"><span className="project-client">Ditsogn.dk</span><h3>Mindre administration.<br/>Mere fællesskab.</h3><p>Vi har udviklet software til Ditsogn.dk, der samler kirkens hjemmeside, kalender, nyheder og tilmeldinger i én overskuelig platform.</p><p>Med Sogn.dk-synkronisering og en enkel administration bliver det lettere at holde information opdateret. Så kirkens medarbejdere kan bruge mere tid på livet i sognet.</p><a className="text-link" href="https://ditsogn.dk" target="_blank" rel="noreferrer">Oplev Ditsogn.dk <Arrow/></a></div><div className="project-art"><div className="project-artifact parish-board"><div className="artifact-bar"><span>Ditsogn.dk</span><span>VISUELT KONCEPT</span></div><div className="parish-board-content"><CalendarDays size={28} strokeWidth={1.2}/><span className="artifact-eyebrow">HELE SOGNET. SAMLET.</span><h4>Plads til fællesskab.</h4><div className="parish-week">{['M','T','O','T','F','L','S'].map((day,i)=><span className={i===6?'selected-day':''} key={i}>{day}<b>{i+7}</b></span>)}</div><div className="parish-event"><span>10:00</span><div><strong>Gudstjeneste</strong><span>En del af livet i sognet</span></div><Users size={18}/></div><div className="artifact-note"><Check size={15}/><span>Én opdatering. Mere sammenhæng.</span></div></div></div></div></div><div className="project-bottom"><span>FRA SPREDT INFORMATION TIL ET SAMLET SOGN</span><span>DITSOGN.DK <Arrow/></span></div><span className="project-watermark" aria-hidden="true">Together.</span></article>
        <article className="project-card project-structo" lang="da"><div className="project-top"><span>03 / INTELLIGENS TIL BYGGEBRANCHEN</span><span>AI & SOFTWAREUDVIKLING</span></div><div className="project-body"><div className="project-copy"><span className="project-client">Structo</span><h3>Fra komplekse krav.<br/>Til et klart grundlag.</h3><p>Vi har udviklet Structo for at gøre byggeriets regelarbejde enklere. Platformen samler projektdata og officielle kilder, omsætter dem til relevante krav og hjælper rådgivere med at gennemgå deres materiale med AI.</p><p>Et sammenhængende overblik fra ejendom til krav. Mindre tid på at lede — mere tid til at skabe.</p><a className="text-link" href="https://structo.dk" target="_blank" rel="noreferrer">Oplev Structo <Arrow/></a></div><div className="project-art"><div className="project-artifact requirements-board"><div className="artifact-bar"><span>structo</span><span>VISUELT KONCEPT</span></div><div className="requirements-content"><span className="artifact-eyebrow">FRA PROJEKTDATA TIL KLARHED</span><h4>Et stærkere grundlag.</h4>{['Ejendommens data','De relevante krav','Dit projektmateriale'].map((label,i)=><div className="requirement-step" key={label}><span>0{i+1}</span><strong>{label}</strong><ArrowRight size={18}/></div>)}<div className="artifact-note"><Sparkles size={16}/><span>Forbundet af intelligent software.</span></div></div></div></div></div><div className="project-bottom"><span>FRA MANUELT REGELARBEJDE TIL PROJEKTOVERBLIK</span><span>STRUCTO.DK <Arrow/></span></div><span className="project-watermark" aria-hidden="true">Forward.</span></article>
      </div>
    </section>

    <section className="method section-pad"><div className="section-marker"><span className="eyebrow">04 / HOW CHANGE HAPPENS</span><Plus size={18}/></div><div className="method-heading"><h2>Big change.<br/>Simple beginnings.</h2><p>We don’t start with technology.<br/>We start with something worth solving.</p></div><div className="approach-list">{[{n:'01',title:'Find the friction.',description:'The spreadsheets. The endless searching. The “there must be a better way.” That’s where we begin.',tag:'SEE THE OPPORTUNITY'},{n:'02',title:'Rethink the work.',description:'We bring human understanding and artificial intelligence together to build a better way through.',tag:'BUILD WITH INTELLIGENCE'},{n:'03',title:'Make room for more.',description:'Less effort on the repetitive. More energy for the remarkable. Software that gives ambition room to grow.',tag:'UNLOCK HUMAN POTENTIAL'}].map(item=><article className="approach-row" key={item.n}><span className="approach-number">/{item.n}</span><div><h3>{item.title}</h3><p>{item.description}</p></div><span className="approach-tag">{item.tag}</span><MoveUpRight size={28} strokeWidth={1}/></article>)}</div></section>

    <section className="possibility"><span className="eyebrow">LESS OF WHAT HOLDS US BACK. MORE OF WHAT MOVES US.</span><div className="possibility-lines" aria-label="Less friction. More future."><div className="possibility-line one" aria-hidden="true">Less friction. <span>Less friction.</span></div><div className="possibility-line two" aria-hidden="true"><span>More future.</span> More future.</div></div><p>We believe the next revolution is a quieter one.<br/>Work that just works. People free to do more.<br/>A world moving forward, one simple idea at a time.</p><span className="possibility-footnote">THAT’S THE FUTURE WE’RE BUILDING.</span></section>

    <footer id="contact" className="site-footer"><div className="footer-top"><span className="eyebrow"><i className="status-dot"/> GOOD CONVERSATIONS BUILD GREAT THINGS.</span><a href="#top" className="back-top">BACK TO TOP ↑</a></div><div className="footer-callout"><h2>Complex challenge?<br/><a href="mailto:mail@structo.dk">Let’s make it simple.<ArrowUpRight strokeWidth={1}/></a></h2><span className="footer-asterisk" aria-hidden="true">✳</span></div><div className="footer-contact"><a href="mailto:mail@structo.dk">mail@structo.dk <Arrow/></a><p>Independent minds.<br/>Building a simpler tomorrow.</p></div><div className="footer-wordmark" aria-label="Egekvist & Skovsted">Egekvist <span>&</span> Skovsted<span className="footer-reg">®</span></div><div className="footer-bottom"><span>© {new Date().getFullYear()} EGEKVIST & SKOVSTED</span><span>MADE OF CURIOSITY. POWERED BY AI.</span><button onClick={()=>setPaused(!paused)} aria-pressed={paused}>{paused?<Play size={12}/>:<Pause size={12}/>} MOTION {paused?'OFF':'ON'}</button></div></footer>
    <noscript><style>{'.loader{display:none}.hero-line>span{transform:none!important;opacity:1!important}.system-copy-last{display:none}'}</style></noscript>
  </main>
}
