'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, Plus, MoveUpRight, Pause, Play, Check, FileText, Layers, Sparkles, Sun, Coffee, BookOpen, Heart, CalendarDays, Users, ArrowRight } from 'lucide-react';
import Scene from './scene';

const Arrow = () => <ArrowUpRight size={19} strokeWidth={1.5}/>;
const phrase = 'The world is complex. Work doesn’t have to be.';

export default function Home() {
  const root = useRef<HTMLElement>(null);
  const [loaded,setLoaded] = useState(false);
  const [introGone,setIntroGone] = useState(false);
  const [paused,setPaused] = useState(false);
  const readyRef = useRef(false);
  const onReady = useCallback(()=>{readyRef.current=true;},[]);
  useEffect(()=> { const media=window.matchMedia('(prefers-reduced-motion: reduce)'); setPaused(media.matches);const change=()=>setPaused(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
  useEffect(()=> {
    const start=performance.now();
    const interval=window.setInterval(()=>{
      const elapsed=performance.now()-start;
      if ((elapsed>1700 && readyRef.current) || elapsed>2300 || paused) {setLoaded(true);window.clearInterval(interval);}
    },45);
    return()=>window.clearInterval(interval);
  },[paused]);
  useEffect(()=> {
    if(!loaded) return;
    const timeout=window.setTimeout(()=>setIntroGone(true),800);
    return()=>window.clearTimeout(timeout);
  },[loaded]);
  useEffect(()=> {
    if(!loaded) return;
    let stop=()=>{},disposed=false;
    Promise.all([import('gsap'),import('gsap/ScrollTrigger'),import('lenis')]).then(([{gsap},{ScrollTrigger},{default:Lenis}])=>{
      if(disposed)return;
      gsap.registerPlugin(ScrollTrigger);
      const lenis = paused ? null : new Lenis({duration:1.15,smoothWheel:true,anchors:true});
      const tick=(time:number)=>lenis?.raf(time*1000);
      if(lenis){lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(tick);}
      const ctx=gsap.context(()=>{
        if(paused)return;
        gsap.fromTo('.hero-line > span',{yPercent:115,rotateX:-45},{yPercent:0,rotateX:0,duration:1.35,stagger:.13,ease:'power4.out',delay:.2});
        gsap.fromTo('.hero-art',{scale:.62,rotation:-24,opacity:0},{scale:1,rotation:0,opacity:1,duration:1.8,ease:'power3.out',delay:.05});
        gsap.fromTo('.site-header,.hero-top,.hero-bottom,.hero-caption',{y:20,opacity:0},{y:0,opacity:1,duration:1,stagger:.1,delay:.45});
        gsap.to('.hero h1',{y:-100,rotateX:12,scale:.96,transformOrigin:'left center',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});
        gsap.fromTo('.manifesto-word',{color:'#434954'},{color:'#f0f2f6',stagger:.12,ease:'none',scrollTrigger:{trigger:'.manifesto-copy',start:'top 78%',end:'bottom 40%',scrub:.6}});
        gsap.fromTo('.intro-bottom',{y:65},{y:0,scrollTrigger:{trigger:'.intro-bottom',start:'top bottom',end:'top 65%',scrub:1}});
        gsap.to('.system-copy-first',{y:-55,opacity:0,scrollTrigger:{trigger:'.transformation',start:'top -20%',end:'top -65%',scrub:.7}});
        gsap.fromTo('.system-copy-last',{y:55,opacity:0},{y:0,opacity:1,scrollTrigger:{trigger:'.transformation',start:'top -55%',end:'top -95%',scrub:.7}});
        gsap.to('.system-progress-fill',{scaleY:1,ease:'none',scrollTrigger:{trigger:'.transformation',start:'top top',end:'bottom bottom',scrub:.3}});
        gsap.to('.system-label-before',{opacity:.2,scrollTrigger:{trigger:'.transformation',start:'top -35%',end:'top -80%',scrub:.5}});
        gsap.fromTo('.system-label-after',{opacity:.2},{opacity:1,scrollTrigger:{trigger:'.transformation',start:'top -35%',end:'top -80%',scrub:.5}});
        gsap.fromTo('.work-visual',{rotateX:14,rotateY:-5,scale:.84},{rotateX:0,rotateY:0,scale:1,scrollTrigger:{trigger:'.work-visual-wrap',start:'top 92%',end:'top 14%',scrub:1}});
        gsap.fromTo('.feature-screen',{rotateY:-9,rotateX:7,y:40,scale:.92},{rotateY:0,rotateX:0,y:-15,scale:1,scrollTrigger:{trigger:'.work-visual',start:'top 90%',end:'bottom 30%',scrub:1}});
        gsap.fromTo('.structo-interface',{y:100,rotateY:-12,rotateX:10},{y:-35,rotateY:0,rotateX:0,scrollTrigger:{trigger:'.work-visual',start:'top 75%',end:'bottom 25%',scrub:1}});
        gsap.utils.toArray<HTMLElement>('.project-card').forEach((card,index)=>{
          gsap.fromTo(card,{rotateX:14,rotateY:index%2 ? 5 : -5,scale:.91,y:90},{rotateX:0,rotateY:0,scale:1,y:0,ease:'none',scrollTrigger:{trigger:card,start:'top 95%',end:'top 18%',scrub:1}});
          gsap.fromTo(card.querySelector('.project-artifact'),{rotateY:18,rotateX:9,x:45,y:85,scale:.85},{rotateY:0,rotateX:0,x:0,y:-12,scale:1,ease:'none',scrollTrigger:{trigger:card,start:'top 92%',end:'bottom 38%',scrub:1.1}});
          gsap.fromTo(card.querySelector('.project-screen'),{rotateY:-15,rotateX:9,x:-20,y:65,scale:.93},{rotateY:0,rotateX:0,x:0,y:-12,scale:1,ease:'none',scrollTrigger:{trigger:card,start:'top 92%',end:'bottom 38%',scrub:1.2}});
          gsap.fromTo(card.querySelector('.project-watermark'),{xPercent:12},{xPercent:-12,scrollTrigger:{trigger:card,start:'top bottom',end:'bottom top',scrub:1}});
        });
        gsap.fromTo('.other-heading h2',{x:-65},{x:0,scrollTrigger:{trigger:'.other-heading',start:'top 90%',end:'top 45%',scrub:.8}});
        gsap.utils.toArray<HTMLElement>('.approach-row').forEach(el=>gsap.fromTo(el,{rotateX:18,y:65},{rotateX:0,y:0,scrollTrigger:{trigger:el,start:'top 95%',end:'top 60%',scrub:.8}}));
        gsap.utils.toArray<HTMLElement>('.about-title-line > span').forEach((line,index)=>gsap.fromTo(line,{yPercent:80,rotateX:-35},{yPercent:0,rotateX:0,ease:'none',scrollTrigger:{trigger:'.about-heading',start:`top ${85-index*8}%`,end:'top 32%',scrub:.9}}));
        gsap.fromTo('.about-sculpture',{y:70,rotation:-12},{y:-45,rotation:10,scrollTrigger:{trigger:'.about-intro',start:'top bottom',end:'bottom top',scrub:1.2}});
        gsap.utils.toArray<HTMLElement>('.team-principle').forEach((el,index)=>gsap.fromTo(el,{y:65+index*20,rotateX:18},{y:0,rotateX:0,scrollTrigger:{trigger:'.team-principles',start:'top 92%',end:'top 52%',scrub:1}}));
        gsap.fromTo('.collective-progress span',{scaleX:0},{scaleX:1,ease:'none',scrollTrigger:{trigger:'.collective-sculpture',start:'top 85%',end:'top 5%',scrub:1}});
        gsap.fromTo('.founder-portrait-frame',{rotateY:-11,rotateX:7,scale:.93},{rotateY:0,rotateX:0,scale:1,scrollTrigger:{trigger:'.founder-profile',start:'top 87%',end:'top 16%',scrub:1.1}});
        gsap.fromTo('.founder-portrait-frame img',{scale:1.12,yPercent:-3},{scale:1.03,yPercent:3,scrollTrigger:{trigger:'.founder-profile',start:'top bottom',end:'bottom top',scrub:1.3}});
        gsap.fromTo('.founder-caption',{y:35,z:20},{y:-10,z:70,scrollTrigger:{trigger:'.founder-profile',start:'top 85%',end:'bottom 55%',scrub:1}});
        gsap.fromTo('.founder-copy',{y:45},{y:0,scrollTrigger:{trigger:'.founder-profile',start:'top 85%',end:'top 25%',scrub:.9}});
        gsap.fromTo('.europe-ambition .ambition-rule',{scaleX:0},{scaleX:1,ease:'none',scrollTrigger:{trigger:'.europe-ambition',start:'top 90%',end:'top 45%',scrub:1}});
        gsap.utils.toArray<HTMLElement>('.venture-title-line > span').forEach((line,index)=>gsap.fromTo(line,{yPercent:85,rotateX:-35},{yPercent:0,rotateX:0,ease:'none',scrollTrigger:{trigger:'.venture-heading',start:`top ${92-index*6}%`,end:'top 38%',scrub:1}}));
        gsap.fromTo('.venture-detail',{y:45},{y:0,scrollTrigger:{trigger:'.venture-detail',start:'top 95%',end:'top 65%',scrub:1}});
        gsap.fromTo('.venture-rule',{scaleX:0},{scaleX:1,ease:'none',scrollTrigger:{trigger:'.venture-section',start:'top 90%',end:'top 30%',scrub:1}});
        gsap.fromTo('.possibility-line.one',{xPercent:12},{xPercent:-12,scrollTrigger:{trigger:'.possibility',start:'top bottom',end:'bottom top',scrub:1}});
        gsap.fromTo('.possibility-line.two',{xPercent:-14},{xPercent:8,scrollTrigger:{trigger:'.possibility',start:'top bottom',end:'bottom top',scrub:1}});
        gsap.fromTo('.footer-wordmark',{yPercent:40,rotateX:45},{yPercent:0,rotateX:0,scrollTrigger:{trigger:'.site-footer',start:'top 70%',end:'bottom bottom',scrub:1}});
        gsap.to('.footer-asterisk',{rotation:150,scrollTrigger:{trigger:'.site-footer',start:'top bottom',end:'bottom bottom',scrub:1}});
      },root);
      const refresh=()=>ScrollTrigger.refresh();document.fonts.ready.then(refresh);window.addEventListener('load',refresh);ScrollTrigger.refresh();
      stop=()=>{ctx.revert();gsap.ticker.remove(tick);lenis?.destroy();window.removeEventListener('load',refresh);};
    });
    return()=>{disposed=true;stop();};
  },[loaded,paused]);

  return <main ref={root} className={`${loaded?'is-ready':''} ${paused?'motion-paused':''}`}>
    <a className="skip-link" href="#approach">Skip to content</a>
    {!introGone && <div className={`signature-loader ${loaded?'signature-exit':''}`} role="status" aria-label="Loading Oakbranch" aria-hidden={loaded}>
      <div className="signature-centre" aria-hidden="true">
        <div className="signature-object"><Scene kind="signature" paused={paused}/></div>
        <div className="signature-wordmark"><span>Oakbranch</span></div>
        <span className="signature-caption">COMPLEXITY, REIMAGINED.</span>
        <div className="signature-track"><span/></div>
      </div>
      <span className="signature-footnote" aria-hidden="true">INDEPENDENT MINDS. SHARED AMBITION.</span>
    </div>}
    <header className="site-header"><a className="wordmark" href="#top" aria-label="Oakbranch home">Oakbranch</a><nav aria-label="Main navigation"><a href="#approach">Our approach</a><a href="#work">Selected work <sup>03</sup></a><a href="#other-work">Other work</a><a href="#about">About us</a></nav><a className="contact-nav" href="mailto:mail@structo.dk">Let’s talk <span><Arrow/></span></a></header>
    <section className="hero" id="top"><div className="hero-top"><span className="eyebrow"><i className="status-dot"/> INDEPENDENT MINDS. INTELLIGENT SOFTWARE.</span><span className="edition">BUILT IN DENMARK. THINKING BEYOND.</span></div><div className="hero-art"><Scene kind="hero" paused={paused} onReady={onReady}/></div><h1 aria-label="Making complex work feel simple"><span className="hero-line"><span>Making complex</span></span><span className="hero-line"><span>work feel <em>simple.</em></span></span></h1><div className="hero-bottom"><p>We turn the work that slows the world down<br className="desktop-break"/> into software that moves it forward.</p><a className="circle-link" href="#approach"><span>SCROLL TO SIMPLIFY</span><i><ArrowDown size={20}/></i></a></div><div className="hero-caption"><span>HUMAN AMBITION × ARTIFICIAL INTELLIGENCE</span><span>01 — ∞</span></div></section>

    <section className="intro section-pad" id="approach"><div className="section-marker"><span className="eyebrow">01 / THE WAY WE SEE IT</span><Plus size={18}/></div><h2 className="manifesto-copy">{phrase.split(' ').map((word,i)=><span className="manifesto-word" key={i}>{word} </span>)}</h2><div className="intro-bottom"><span className="mini-asterisk" aria-hidden="true">✳</span><div><p>Too many brilliant minds are busy doing work that shouldn’t be hard.</p><p>We find the manual, the repetitive, the unnecessarily complex. Then we use AI to turn it into something remarkably simple. So people can get back to moving the world forward.</p></div></div></section>

    <section className="transformation" id="transformation"><div className="system-sticky"><div className="system-top"><span className="eyebrow">COMPLEXITY, RECONSIDERED.</span><span className="eyebrow">SCROLL TO TRANSFORM ↓</span></div><div className="system-copy"><div className="system-copy-first"><span className="small-index">[ BEFORE ]</span><h2>So much work.<br/>So little flow.</h2><p>Scattered information. Repeated tasks.<br/>Potential, waiting to be unlocked.</p></div><div className="system-copy-last"><span className="small-index">[ AFTER ]</span><h2>Everything<br/><em>falls into place.</em></h2><p>One intelligent system.<br/>A simpler way to move forward.</p></div></div><div className="system-art"><Scene kind="system" paused={paused}/></div><div className="system-progress"><span>01</span><div><i className="system-progress-fill"/></div><span>02</span></div><div className="system-bottom"><span className="system-label-before">FROM FRICTION</span><span className="system-bottom-line"/><span className="system-label-after">TO FLOW</span></div></div></section>

    <section className="work-section section-pad" id="work" lang="en"><div className="section-marker"><span className="eyebrow">02 / IDEAS, OUT IN THE WORLD</span><span className="eyebrow">SELECTED WORK — 01</span></div><div className="work-heading"><h2>Less busywork.<br/><span>More possibility.</span></h2><p>A better way of working isn’t a distant idea.<br/>It’s something we’re building. Right now.</p></div><div className="work-visual-wrap"><div className="work-visual screenshot-feature"><div className="feature-screen"><div className="screen-toolbar" aria-hidden="true"><span className="screen-dots"><i/><i/><i/></span><span>structo.dk</span><ArrowUpRight size={14}/></div><img className="feature-screenshot" src="/structo-website.jpg" alt="Structo website showing property data, building requirements, and AI-assisted review" width="2560" height="1424" loading="lazy"/></div><div className="structo-interface" aria-label="Illustrative Structo project overview"><div className="interface-top"><span><span className="structo-icon">▥</span> structo</span><span className="concept-label">PLATFORM CONCEPT</span></div><div className="interface-content"><span className="interface-kicker">YOUR PROJECT. CONNECTED.</span><h3>From rules to clarity.</h3><div className="interface-project"><Layers size={17}/><span>Project overview</span><span className="project-status"><i/> Ready to explore</span></div>{[['Local plans','Find what matters'],['Building regulations','Understand the requirements'],['Regulatory requirements','Move your project forward']].map(([title,text])=><div className="interface-row" key={title}><FileText size={16}/><div><strong>{title}</strong><span>{text}</span></div><Check size={15}/></div>)}<div className="interface-ai"><Sparkles size={15}/><span>Less searching. More clarity.</span></div></div></div></div></div>
      <div className="work-details" lang="en"><div className="work-title"><span className="eyebrow">STRUCTO / AI FOR THE BUILT WORLD</span><h3>Less time on regulations.<br/><span>More time for architecture.</span></h3><a href="https://structo.dk" target="_blank" rel="noreferrer" className="text-link">Explore Structo <Arrow/></a></div><div className="work-description"><p>Structo helps architects, architectural technologists, and building consultants spend less time finding and reviewing regulations and requirements.</p><p>The platform brings together relevant project information, making it easier to find, understand, and work with local plans, building regulations, and other regulatory requirements.</p><p>The goal is simple: less time on manual regulatory work. More time for design, advice, and architecture.</p></div></div>
    </section>

    <section className="other-work" id="other-work" aria-labelledby="other-work-title">
      <div className="other-heading"><div className="section-marker"><span className="eyebrow">03 / SOFTWARE, WITH A PURPOSE</span><span className="eyebrow">THREE PROJECTS. ONE MINDSET.</span></div><h2 id="other-work-title">Other work<span>®</span></h2><div className="other-intro"><p>Different worlds.<br/>The same belief in simple.</p><span className="eyebrow">EXPLORE THE PROJECTS <ArrowDown size={16}/></span></div></div>
      <div className="projects-stage"><div className="portfolio-orbit"><Scene kind="portfolio" paused={paused}/></div>
        <article className="project-card project-picto" lang="en"><div className="project-top"><span>01 / VISUAL COMMUNICATION</span><span>SOFTWARE DEVELOPMENT</span></div><div className="project-body"><div className="project-copy"><span className="project-client">PictoPartner</span><h3>More structure.<br/>More connection.</h3><p>We developed the software behind PictoPartner: a platform that brings pictograms, activities, and visual support tools together for care settings, specialist services, and families.</p><p>From a shared library and custom pictograms to print-ready materials. Less manual preparation makes more room for professional care and meaningful connection.</p><a className="text-link" href="https://pictopartner.dk" target="_blank" rel="noreferrer">Explore PictoPartner <Arrow/></a></div><div className="project-art"><figure className="project-photo project-screen"><div className="screen-toolbar" aria-hidden="true"><span className="screen-dots"><i/><i/><i/></span><span>pictopartner.dk</span><ArrowUpRight size={12}/></div><img src="/pictopartner-website.jpg" alt="PictoPartner website showing pictograms, templates, activities, and social stories" width="2560" height="1428" loading="lazy" decoding="async"/></figure><div className="project-artifact picto-board"><div className="artifact-bar"><span>PictoPartner</span><span>VISUAL CONCEPT</span></div><div className="picto-board-content"><span className="artifact-eyebrow">SMALL STEPS. A CALMER DAY.</span><h4>My day</h4><div className="picto-grid">{[{Icon:Sun,title:'Good morning'},{Icon:Coffee,title:'Breakfast'},{Icon:BookOpen,title:'Reading time'},{Icon:Heart,title:'Together'}].map(({Icon,title})=><div className="picto-tile" key={title}><Icon strokeWidth={1.2}/><span>{title}</span></div>)}</div><div className="artifact-note"><Check size={15}/><span>Clarity everyone can understand.</span></div></div></div></div></div><div className="project-bottom"><span>FROM MANUAL PREPARATION TO VISUAL CLARITY</span><span>PICTOPARTNER.DK <Arrow/></span></div><span className="project-watermark" aria-hidden="true">Clarity.</span></article>
        <article className="project-card project-parish" lang="en"><div className="project-top"><span>02 / CONNECTED COMMUNITIES</span><span>SOFTWARE DEVELOPMENT</span></div><div className="project-body"><div className="project-copy"><span className="project-client">Ditsogn.dk</span><h3>Less administration.<br/>More community.</h3><p>We developed software for Ditsogn.dk that brings church websites, calendars, news, and event registrations into one straightforward platform.</p><p>Sogn.dk synchronisation and simple administration make it easier to keep information up to date. So church teams can spend more time on the life of their parish.</p><a className="text-link" href="https://ditsogn.dk" target="_blank" rel="noreferrer">Explore Ditsogn.dk <Arrow/></a></div><div className="project-art"><figure className="project-photo project-screen"><div className="screen-toolbar" aria-hidden="true"><span className="screen-dots"><i/><i/><i/></span><span>ditsogn.dk</span><ArrowUpRight size={12}/></div><img src="/ditsogn-website.jpg" alt="Ditsogn.dk website showing its church website and parish management platform" width="2560" height="1424" loading="lazy" decoding="async"/></figure><div className="project-artifact parish-board"><div className="artifact-bar"><span>Ditsogn.dk</span><span>VISUAL CONCEPT</span></div><div className="parish-board-content"><CalendarDays size={28} strokeWidth={1.2}/><span className="artifact-eyebrow">THE WHOLE PARISH. CONNECTED.</span><h4>Room for community.</h4><div className="parish-week">{['M','T','W','T','F','S','S'].map((day,i)=><span className={i===6?'selected-day':''} key={i}>{day}<b>{i+7}</b></span>)}</div><div className="parish-event"><span>10:00</span><div><strong>Church service</strong><span>Part of parish life</span></div><Users size={18}/></div><div className="artifact-note"><Check size={15}/><span>One update. Everything connected.</span></div></div></div></div></div><div className="project-bottom"><span>FROM SCATTERED INFORMATION TO A CONNECTED PARISH</span><span>DITSOGN.DK <Arrow/></span></div><span className="project-watermark" aria-hidden="true">Together.</span></article>
        <article className="project-card project-structo" lang="en"><div className="project-top"><span>03 / INTELLIGENCE FOR THE BUILT WORLD</span><span>AI & SOFTWARE DEVELOPMENT</span></div><div className="project-body"><div className="project-copy"><span className="project-client">Structo</span><h3>From complex rules.<br/>To clear foundations.</h3><p>We developed Structo to simplify regulatory work in construction. It connects project data and official sources, identifies relevant requirements, and helps consultants review their materials with AI.</p><p>One connected view, from property to requirements. Less time searching. More time creating.</p><a className="text-link" href="https://structo.dk" target="_blank" rel="noreferrer">Explore Structo <Arrow/></a></div><div className="project-art"><figure className="project-photo project-screen"><div className="screen-toolbar" aria-hidden="true"><span className="screen-dots"><i/><i/><i/></span><span>structo.dk</span><ArrowUpRight size={12}/></div><img src="/structo-website.jpg" alt="Structo website showing its AI-assisted building requirements platform" width="2560" height="1424" loading="lazy" decoding="async"/></figure><div className="project-artifact requirements-board"><div className="artifact-bar"><span>structo</span><span>VISUAL CONCEPT</span></div><div className="requirements-content"><span className="artifact-eyebrow">FROM PROJECT DATA TO CLARITY</span><h4>A stronger foundation.</h4>{['Property data','Relevant requirements','Your project materials'].map((label,i)=><div className="requirement-step" key={label}><span>0{i+1}</span><strong>{label}</strong><ArrowRight size={18}/></div>)}<div className="artifact-note"><Sparkles size={16}/><span>Connected by intelligent software.</span></div></div></div></div></div><div className="project-bottom"><span>FROM MANUAL RULE CHECKS TO PROJECT CLARITY</span><span>STRUCTO.DK <Arrow/></span></div><span className="project-watermark" aria-hidden="true">Forward.</span></article>
      </div>
    </section>

    <section className="method section-pad"><div className="section-marker"><span className="eyebrow">04 / HOW CHANGE HAPPENS</span><Plus size={18}/></div><div className="method-heading"><h2>Big change.<br/>Simple beginnings.</h2><p>We don’t start with technology.<br/>We start with something worth solving.</p></div><div className="approach-list">{[{n:'01',title:'Find the friction.',description:'The spreadsheets. The endless searching. The “there must be a better way.” That’s where we begin.',tag:'SEE THE OPPORTUNITY'},{n:'02',title:'Rethink the work.',description:'We bring human understanding and artificial intelligence together to build a better way through.',tag:'BUILD WITH INTELLIGENCE'},{n:'03',title:'Make room for more.',description:'Less effort on the repetitive. More energy for the remarkable. Software that gives ambition room to grow.',tag:'UNLOCK HUMAN POTENTIAL'}].map(item=><article className="approach-row" key={item.n}><span className="approach-number">/{item.n}</span><div><h3>{item.title}</h3><p>{item.description}</p></div><span className="approach-tag">{item.tag}</span><MoveUpRight size={28} strokeWidth={1}/></article>)}</div></section>

    <section className="about-section" id="about" aria-labelledby="about-title">
      <div className="section-marker"><span className="eyebrow">05 / ABOUT US</span><span className="eyebrow">INDEPENDENT IN SPIRIT. UNITED BY PURPOSE.</span></div>
      <div className="about-intro"><div className="about-heading"><h2 id="about-title"><span className="about-title-line"><span>Curious minds.</span></span><span className="about-title-line"><span>Shared <em>ambition.</em></span></span></h2><p className="about-lead">We see a world full of things<br/>that could work a little better.</p></div><div className="about-sculpture"><Scene kind="about" paused={paused}/></div></div>
      <div className="team-story"><div className="team-story-visual"><span className="eyebrow">THE PEOPLE BEHIND THE POSSIBILITIES</span><figure className="collective-sculpture" id="team-collective"><div className="collective-canvas"><Scene kind="collective" paused={paused}/></div><figcaption><span>DIFFERENT PERSPECTIVES.</span><span>ONE SHARED AMBITION.</span></figcaption><div className="collective-progress" aria-hidden="true"><span/></div></figure></div><div className="team-story-copy"><p>We’re independent thinkers and hands-on builders, brought together by a simple instinct: when something feels harder than it should, there’s probably a better way.</p><p>Our work starts with listening. To the people doing the work. To the details that get overlooked. To the small frustrations that add up. Then we bring curiosity, craft, and intelligent software together to turn those observations into useful products.</p><p>Different perspectives. A shared standard. Technology should feel thoughtful, work beautifully, and leave people with more room to do what matters.</p></div></div>
      <div className="team-principles">{[{number:'01',title:'Stay curious.',copy:'The best ideas begin with a better question.'},{number:'02',title:'Build with purpose.',copy:'Make something useful. Then make it feel effortless.'},{number:'03',title:'Think beyond.',copy:'Solve today’s problem with tomorrow in mind.'}].map(item=><article className="team-principle" key={item.number}><span>{item.number} /</span><h3>{item.title}</h3><p>{item.copy}</p></article>)}</div>
      <div className="founder-section" id="founder"><div className="section-marker"><span className="eyebrow">06 / MEET OUR FOUNDER</span><Plus size={18}/></div><div className="founder-profile"><figure className="founder-portrait"><div className="founder-portrait-frame"><img src="/svante-founder.jpg" alt="Svante Egekvist Skovsted, founder of Oakbranch" width="772" height="776" loading="lazy" decoding="async"/></div><figcaption className="founder-caption"><span>Svante Egekvist Skovsted</span><span>FOUNDER & SOFTWARE DEVELOPER</span></figcaption></figure><div className="founder-copy"><span className="eyebrow">A SIMPLE IDEA. A LONG-TERM VISION.</span><h2>Built on curiosity.<br/><span>Driven by possibility.</span></h2><p className="founder-intro">Our founder, Svante Egekvist Skovsted, is a Danish entrepreneur and software developer focused on artificial intelligence and SaaS.</p><p>He founded Oakbranch with the ambition of using AI and modern software to solve complex, real-world problems.</p><p>His focus is on industries where work is still manual, fragmented, or unnecessarily complicated — and on building technology that makes those processes simpler and more efficient.</p><div className="founder-signoff"><span>Svante Egekvist Skovsted</span><span>OAKBRANCH</span></div></div></div><div className="europe-ambition"><div className="ambition-rule"/><span className="eyebrow">ROOTED IN DENMARK. LOOKING AHEAD.</span><div><h3>Meaningful products.<br/><em>A stronger Europe.</em></h3><p>Svante’s long-term ambition is to build technology companies that create meaningful products while contributing to a stronger, more technologically independent Europe.</p></div></div></div>
    </section>

    <section className="venture-section" id="build-with-us" aria-labelledby="venture-title">
      <div className="section-marker"><span className="eyebrow">07 / BUILD WITH US</span><span className="eyebrow">EUROPEAN AMBITION. SHARED.</span></div>
      <div className="venture-layout">
        <div className="venture-heading"><h2 id="venture-title"><span className="venture-title-line"><span>The future of</span></span><span className="venture-title-line"><span>European software</span></span><span className="venture-title-line"><span><em>starts here.</em></span></span></h2></div>
        <figure className="venture-art"><div className="venture-canvas"><Scene kind="venture" paused={paused}/></div><figcaption>YOUR EXPERTISE × OUR TECHNOLOGY</figcaption></figure>
        <div className="venture-detail"><h3>You know the industry.<br/>Let’s build what comes next.</h3><p>If you’re a professional who sees a better way through a complex workflow in your industry, let’s build a company around it.</p><p>You bring the insight. We bring software and AI. Together, we can turn a real problem into a meaningful product—and help shape a more technologically independent Europe.</p><a className="venture-contact" href="mailto:mail@egekvistogskovsted.dk"><span><strong>Start a conversation</strong><span>mail@egekvistogskovsted.dk</span></span><i><ArrowUpRight size={25} strokeWidth={1.4}/></i></a></div>
      </div>
      <div className="venture-rule" aria-hidden="true"/><div className="venture-bottom"><span>BUILT FROM EXPERIENCE.</span><span>MADE FOR WHAT’S NEXT.</span></div>
    </section>

    <section className="possibility"><span className="eyebrow">LESS OF WHAT HOLDS US BACK. MORE OF WHAT MOVES US.</span><div className="possibility-lines" aria-label="Less friction. More future."><div className="possibility-line one" aria-hidden="true">Less friction. <span>Less friction.</span></div><div className="possibility-line two" aria-hidden="true"><span>More future.</span> More future.</div></div><p>We believe the next revolution is a quieter one.<br/>Work that just works. People free to do more.<br/>A world moving forward, one simple idea at a time.</p><span className="possibility-footnote">THAT’S THE FUTURE WE’RE BUILDING.</span></section>

    <footer id="contact" className="site-footer"><div className="footer-top"><span className="eyebrow"><i className="status-dot"/> GOOD CONVERSATIONS BUILD GREAT THINGS.</span><a href="#top" className="back-top">BACK TO TOP ↑</a></div><div className="footer-callout"><h2>Complex challenge?<br/><a href="mailto:mail@structo.dk">Let’s make it simple.<ArrowUpRight strokeWidth={1}/></a></h2><span className="footer-asterisk" aria-hidden="true">✳</span></div><div className="footer-contact"><a href="mailto:mail@structo.dk">mail@structo.dk <Arrow/></a><p>Independent minds.<br/>Building a simpler tomorrow.</p></div><div className="footer-wordmark" aria-label="Oakbranch">Oakbranch<span className="oak-footer-dot">.</span></div><div className="footer-bottom"><span>© {new Date().getFullYear()} OAKBRANCH</span><span>MADE OF CURIOSITY. POWERED BY AI.</span><button onClick={()=>setPaused(!paused)} aria-pressed={paused}>{paused?<Play size={12}/>:<Pause size={12}/>} MOTION {paused?'OFF':'ON'}</button></div></footer>
    <noscript><style>{'.signature-loader{display:none}.hero-line>span{transform:none!important;opacity:1!important}.system-copy-last{display:none}'}</style></noscript>
  </main>
}
